[package]
name = "fluence_sqlite"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "fluence_sqlite"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.8.0"
marine-sqlite-connector = "0.8.0"

[dev-dependencies]
marine-rs-sdk-test = "0.9.0"
